----------------------------- MODULE AbsJupiter -----------------------------
(*
Abstract Jupiter
*)

EXTENDS Naturals, Order, AdditionalSequenceOperators

CONSTANTS
    Client, \* the set of client replicas
    Server, \* the unique server replica
    O,      \* the set of original operations
    co,     \* the client order in which each client generates its operations
    so,     \* the server order in which the server processes operations
    hb      \* the happened-before relation

Replica == Client \cup {Server} \* all replicas
sigma == [O |-> O, co |-> co, so |-> so, hb |-> hb] \* the schedule

ASSUME
    /\ O \subseteq Client \X Nat    \* oid = (c, n)
    /\ co \in [Client -> Seq(O)]    \* strict total order (for each client) represented by sequence
    /\ so \in Seq(O)        \* strict total order represented by sequence
    /\ hb \subseteq O \X O  \* strict partial order

(*
The restriction of co to operations generated by c \in Client.
*)
\* R | c == {<<o1, o2>> \in R: o1.c = c /\ o2.c = c}

Res(csched, oset) ==
    [O |-> oset, co |-> Retain(csched.co, oset), so |-> Retain(csched.so, oset),
     hb |-> csched.hb | oset]

(*
Determine the eo order at client c
*)
RECURSIVE EOR(_)
EOR(csigma) ==
    IF csigma.co = <<>>
    THEN csigma.so
    ELSE LET  o  == Head(csigma.co)
             hbo == LT(hb, o)    \* the set of operation happened-before o
          IN Retain(csigma.so, hbo) 
                \o <<o>> 
                \o EOR(Res(csigma, csigma.O \ (hbo \cup {o})))

(*
eo: execution order, a function mapping each replica r \in Replica to
the order in which the operations are processed at each r.
*)
eo == [r \in Replica |->
        IF r = Server
        THEN so
        ELSE EOR([sigma EXCEPT !.co = @[r]])]
=============================================================================
\* Modification History
\* Last modified Tue Sep 25 20:26:45 CST 2018 by hengxin
\* Created Mon Aug 20 20:23:41 CST 2018 by hengxin